In [ ]:
import numpy as np

In [ ]:
x1_m = np.array([[4.26], [1.33]])
x2_m = np.array([[5.55], [2.03]])
n1 = n2 = 50
s1 = np.array([
    [0.291, 0.049],
    [0.049, 0.075],
])
s2 = np.array([
    [0.212, 0.072],
    [0.072, 0.837]
])

In [ ]:
s_pooled = ( 1 / (n1 + n2 - 2) ) * ( ((n1 - 1) * s1) - ((n2 - 1) * s2) )
print(f"S_pooled is\n{s_pooled}")
s_pooled_i = np.linalg.inv(s_pooled)
print(f"S_pooled^-1 is\n{s_pooled_i}")
a_cap = (x1_m - x2_m).T @ s_pooled_i
print(f"a_cap is\n{a_cap}")
y1_cap = a_cap @ x1_m
print(f"y1_cap is {y1_cap}")
y2_cap = a_cap @ x2_m
print(f"y2_cap is {y2_cap}")
m_cap = (y1_cap + y2_cap) / 2
print(f"The midpoint is {m_cap}")

S_pooled is
[[ 0.0395 -0.0115]
 [-0.0115 -0.381 ]]
S_pooled^-1 is
[[25.09592109 -0.75748843]
 [-0.75748843 -2.60180809]]
a_cap is
[[-31.8434963    2.79842574]]
y1_cap is [[-131.93138802]]
y2_cap is [[-171.05060023]]
The midpoint is [[-151.49099412]]


In [ ]:
x0 = np.array([[5.55, 5.55]])
print(f"x0 is {x0}")
y0_cap = a_cap @ x0.T
print(f"y0_cap is {y0_cap}")
if y0_cap > m_cap:
  print("Allocate x0 to group 1")
else:
  print("Allocate x0 to group 2")

x0 is [[5.55 5.55]]
y0_cap is [[-161.20014162]]
Allocate x0 to group 2
