In [ ]:
import numpy as np

In [ ]:
def mvlr_model(y, x):
  # Design matrix creation
  z = np.insert(
      x, # matrix
      0, # position: start
      1, # insert 1s
      1, # along axis 1 (column)
  )
  return (z.T @ z).I @ z.T @ y

def mvlr_predict(x, model):
  z = np.insert(x, 0, 1, 1)
  return z @ model

mlr_model = mvlr_model
mlr_predict = mvlr_predict

In [ ]:
y = np.matrix([21, 17, 10, 33]).T
x = np.matrix([[2, 4, 6, 2], [110, 123, 205, 65]]).T
beta = mlr_model(y, x)
ycap = mlr_predict(x, beta)
e = ycap - y
print("Multiple linear regression")
print(f"Inputs:\nTarget matrix y\n{y}\nFeature matrix x:\n{x}")
print(f"Estimated model parameter bcap:\n{beta}")
print(f"Estimated values of target:\n{ycap}")
print(f"Error in estimation:\n{e}")

Multiple linear regression
Inputs:
Target matrix y
[[21]
 [17]
 [10]
 [33]]
Feature matrix x:
[[  2 110]
 [  4 123]
 [  6 205]
 [  2  65]]
Estimated model parameter bcap:
[[39.99941793]
 [ 0.61030268]
 [-0.17403958]]
Estimated values of target:
[[22.07566938]
 [21.03376019]
 [ 7.98311991]
 [29.90745052]]
Error in estimation:
[[ 1.07566938]
 [ 4.03376019]
 [-2.01688009]
 [-3.09254948]]


In [ ]:
y1 = np.matrix([[10, 12, 11], [100, 110, 105]]).T
x1 = np.matrix([[9, 8, 7], [62, 58, 64]]).T
beta1 = mvlr_model(y1, x1)
ycap1 = mvlr_predict(x1, beta1)
e1 = ycap1 - y1
print("Multivariate linear regression")
print(f"Inputs:\nTarget matrix y\n{y1}\nFeature matrix x:\n{x1}")
print(f"Estimated model parameter bcap:\n{beta1}")
print(f"Estimated values of target:\n{ycap1}")
print(f"Error in estimation:\n{e1}")

Multivariate linear regression
Inputs:
Target matrix y
[[ 10 100]
 [ 12 110]
 [ 11 105]]
Feature matrix x:
[[ 9 62]
 [ 8 58]
 [ 7 64]]
Estimated model parameter bcap:
[[ 35.8 229. ]
 [ -0.8  -4. ]
 [ -0.3  -1.5]]
Estimated values of target:
[[ 10. 100.]
 [ 12. 110.]
 [ 11. 105.]]
Error in estimation:
[[-5.18696197e-13 -4.49063009e-12]
 [-2.06057393e-13 -2.48689958e-12]
 [-4.40536496e-13 -3.86535248e-12]]
