MLR using scikit-learn

In [ ]:
import numpy as np

In [ ]:
y = np.array([21, 17, 10, 33]).T
x = np.array([[2, 4, 6, 2], [110, 123, 205, 65]]).T

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression().fit(x, y)

In [ ]:
beta = np.insert(model.coef_, 0, model.intercept_, 0)
ycap = model.predict(x)
r_sq = model.score(x, y)
error = ycap - y
sse = sum(error ** 2)

print(
  "Multiple linear regression\n"
  f"Inputs:\nTarget matrix y\n{y}\nFeature matrix x:\n{x}\n"
  f"Estimated model parameters bcap:\n{beta}\n"
  f"Estimated values of target:\n{ycap}\n"
  f"Coefficient of determination (r_sq): {r_sq}\n"
  f"Sum square error: {sse}"
)

Multiple linear regression
Inputs:
Target matrix y
[21 17 10 33]
Feature matrix x:
[[  2 110]
 [  4 123]
 [  6 205]
 [  2  65]]
Estimated model parameters bcap:
[39.99941793  0.61030268 -0.17403958]
Estimated values of target:
[22.07566938 21.03376019  7.98311991 29.90745052]
Coefficient of determination (r_sq): 0.8885741580834946
Sum square error: 31.059953434225868


In [ ]:
# ycap without using predict method
print(np.sum(x * model.coef_, axis = 1) + model.intercept_)

[22.07566938 21.03376019  7.98311991 29.90745052]


In [ ]:
# Predict target for new x
x_new = np.arange(8).reshape(-1, 2)
print(model.predict(x_new))

[39.82537835 40.69790454 41.57043073 42.44295693]
