MLR using statsmodels

In [ ]:
import numpy as np

In [ ]:
y = np.matrix([21, 17, 10, 33]).T
x = np.matrix([[2, 4, 6, 2], [110, 123, 205, 65]]).T

In [ ]:
import statsmodels.api as sm

In [ ]:
# Design matrix creation
z = sm.add_constant(x)

# Create Ordinary Least Squares model and fit the y values to params
model = sm.OLS(y, z)
results = model.fit()

# Print results
beta = results.params
ycap = results.fittedvalues

print("Multiple linear regression")
print(f"Inputs:\nTarget matrix y\n{y}\nFeature matrix x:\n{x}")
print(results.summary())
print(f"\nEstimated model parameters bcap:\n{beta}")
print(f"Estimated values of target:\n{ycap}\n")

Multiple linear regression
Inputs:
Target matrix y
[[21]
 [17]
 [10]
 [33]]
Feature matrix x:
[[  2 110]
 [  4 123]
 [  6 205]
 [  2  65]]
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.889
Model:                            OLS   Adj. R-squared:                  0.666
Method:                 Least Squares   F-statistic:                     3.987
Date:                Sat, 23 Sep 2023   Prob (F-statistic):              0.334
Time:                        08:20:08   Log-Likelihood:                -9.7750
No. Observations:                   4   AIC:                             25.55
Df Residuals:                       1   BIC:                             23.71
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025     

/usr/local/lib/python3.10/dist-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


In [ ]:
# Predict target for new x
x_new = sm.add_constant(np.arange(8).reshape((-1, 2)))
print(results.predict(x_new))

[39.82537835 40.69790454 41.57043073 42.44295693]
