In [ ]:
import numpy as np

In [ ]:
x = np.matrix('1 2 3; 4 5 6')
y = np.matrix([[1, 2, 3], [4, 5, 6]])
sum = x + y
xT = x.T
yT = y.transpose()
dot = np.dot(x, yT)
print(f'x: {x}')
print(f'y: {y}')
print(f'sum: {sum}')
print(f'xT: {xT}')
print(f'yT: {yT}')
print(f'dot: {dot}')
print(f'dot other way: {x.dot(yT)}')
print(f'x: {x}')
print(f'diff: {x - y}')

x: [[1 2 3]
 [4 5 6]]
y: [[1 2 3]
 [4 5 6]]
sum: [[ 2  4  6]
 [ 8 10 12]]
xT: [[1 4]
 [2 5]
 [3 6]]
yT: [[1 4]
 [2 5]
 [3 6]]
dot: [[14 32]
 [32 77]]
dot other way: [[14 32]
 [32 77]]
x: [[1 2 3]
 [4 5 6]]
diff: [[0 0 0]
 [0 0 0]]
